database:
  host: "localhost"
  user: "postgres"
  password: "password123"
  database: "telegrambotdb"
  port: 5432

telegram:
  token: "YOUR_TELEGRAM_BOT_TOKEN"

openai:
  apiKey: "YOUR_OPENAI_API_KEY"
